services:
  # MinIO - S3 compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create MinIO bucket
  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 admin password;
      mc mb minio/iceberg-warehouse || true;
      mc mb minio/trino-spill || true;
      echo 'MinIO buckets created successfully';
      "

  # PostgreSQL - Hive Metastore database
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=hive_metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./hive-metastore/init-hive-schema.sql:/docker-entrypoint-initdb.d/init-hive-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d hive_metastore"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Hive Metastore
  hive-metastore:
    # image: apache/hive:4.0.0
    build:
      context: ./hive-metastore
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - HIVE_LOGLEVEL=INFO
    ports:
      - "9083:9083"
    volumes:
      - ./hive-metastore/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ./hive-metastore/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
    command: >
      /bin/bash -c "
      echo 'Initializing Hive Metastore Schema...';
      /opt/hive/bin/schematool -dbType postgres -initSchema --verbose || echo 'Schema already exists';
      echo 'Starting Hive Metastore...';
      /opt/hive/bin/hive --service metastore --hiveconf hive.root.logger=INFO,console
      "
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 9083 | grep LISTEN || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

  # Trino Coordinator
  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      hive-metastore:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino:ro
    environment:
      - TRINO_ENVIRONMENT=development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/info || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  minio_data:
  postgres_data: